apiVersion: v1
kind: Service
metadata:
  name: {{ include "route-llm-gateway.fullname" . }}-frontend
  labels:
    {{- include "route-llm-gateway.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.service.frontend.type }}
  ports:
    - port: {{ .Values.service.frontend.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "route-llm-gateway.frontend.selectorLabels" . | nindent 4 }}

